Added custom floor selector guide
MapsPeople/documentation pull request #35
Opened 2023-12-28 14:07 UTC by timMikkelsen

2024-01-02 07:17 UTC, matiasholst commented on sdks-and-frameworks/android/custom-floor-selector.md
> +To implement a custom floor selector we expect you to already have a View with a Map using MapControl. Start by creating a class, in this example named; `CustomFloorSelector`. Extend the class with `
Maybe link to the section on setting up mapcontrol?

2024-01-02 07:32 UTC, matiasholst commented on sdks-and-frameworks/android/custom-floor-selector.md
> +Now all that should be left is adding this view component to your layout containing the map and adding it to your `MPMapConfig` when creating `MapControl`. Here is an example layout where the floor s
```suggestion
Now all that is left is adding this view component to your layout containing the map and adding it to your `MPMapConfig` when creating `MapControl`. Here is an example layout where the floor selector is added to a layout.
```

2024-01-02 07:32 UTC, matiasholst commented on sdks-and-frameworks/android/custom-floor-selector.md
> +There we go, you should now have succesfully implemented a custom floor selector into your own app.
```suggestion
There we go, you have now successfully implemented a custom floor selector into your own app.
```

2024-01-02 07:34 UTC, matiasholst requested changes
See 3 comments and suggestions.

2024-01-05 08:52 UTC, timMikkelsen commented
> See 3 comments and suggestions.

@matiasholst Adressed the suggestions and comments now 👍

2024-01-05 09:03 UTC, matiasholst approved these changes

2024-01-05 09:09 UTC, andreeaceachir142 approved these changes
✅

2024-01-05 09:11 UTC, merged